
name: Atomica
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/cicd.yml
  # schedule:
  #   # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  #   - cron: '12 15 * * *'

jobs:
  atomica:
    name: atomica/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.ATOMICA_APP_TOKEN }}
    container:
      image: shadab0565/atomica
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - name: Run Python Scan
        run: semgrep  --config auto --json ${{ github.workspace }}
