name: Atomica
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/cicd.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '12 15 * * *'

jobs:
  atomica:
    name: atomica/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.ATOMICA_APP_TOKEN }}
    container:
      image: shadab0565/atomica-backend
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - name: Debug Repository Contents
        run: |
          echo "Current directory: $(pwd)"
          ls -R ${{ github.workspace }} || echo "Failed to list repository contents"
      - name: Debug Container Contents
        run: |
          ls -R /app || echo "Failed to list /app in container"
      - name: Run Python Scan
        run: python /app/app/scripts/run_scan.py 43de54bc-29c1-4753-900a-e55624e13e18
        env:
          PYTHONPATH: /app/app
